FROM php:7.2.1-apache

# install php extensions
RUN docker-php-ext-install pdo pdo_mysql mysqli

# install composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# install nano and git
RUN apt-get update && apt-get install nano git -y

# enable mod_rewrite
RUN a2enmod rewrite 