USE `todoapp`;

CREATE TABLE IF NOT EXISTS `Task` (
  `id` INT(11) AUTO_INCREMENT PRIMARY KEY,
  `description` VARCHAR(255) NOT NULL,
  `completed` TINYINT(1) NOT NULL,
  `starred` TINYINT(1) NOT NULL,
  `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `modified` DATETIME ON UPDATE CURRENT_TIMESTAMP,
  `due` DATETIME
);
