version: '3'

services:
  php-apache:
    image: php:7.2.1-apache
    build:
      context: ./docker/php-apache
    ports:
      - 4001:80
    volumes:
      - .:/var/www/html
    links:
      - 'mariadb'

  mariadb:
    image: mariadb:10.1
    restart: always
    volumes:
      - todo_db:/var/lib/mysql
      - ./setup/schema.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 3366:3306
    environment:
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'pass'
        MYSQL_DATABASE: 'todoapp'

volumes:
  todo_db:
